import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { app } from 'electron'
import { userLogger } from '../../shared/logger'
import type { AppProfile, GameProfile } from './app-profiles'
import { GAME_PROFILES, APP_PROFILES } from './app-profiles'

const GAME_DOMAINS: Record<string, string[]> = {
	valorant: ['riotgames.com', 'leagueoflegends.com', 'playvalorant.com', 'riotcdn.net', 'riotgames.net'],
	cs2: ['steampowered.com', 'steamcommunity.com', 'steamgames.com', 'valvesoftware.com', 'steamserver.net'],
	dota2: ['steampowered.com', 'steamcommunity.com', 'valvesoftware.com'],
	fortnite: ['epicgames.com', 'unrealengine.com', 'epicgames.dev'],
	apex: ['ea.com', 'origin.com', 'respawn.com'],
	r6siege: ['ubisoft.com', 'ubisoftconnect.com', 'rainbow6.ubisoft.com'],
	pubg: ['pubg.com', 'krafton.com'],
	lol: ['riotgames.com', 'leagueoflegends.com', 'riotcdn.net'],
	gtav: ['rockstargames.com', 'socialclub.rockstargames.com'],
	rust: ['playrust.com', 'rust.facepunch.com', 'facepunch.com'],
}

const VOICE_DOMAINS = {
	discord: ['discord.gg', 'discord.com', 'discordapp.com', 'discord.media', 'cdn.discordapp.com', 'gateway.discord.gg'],
}

const MEDIA_DOMAINS = {
	spotify: ['spotify.com', 'scdn.co', 'spotifycdn.com', 'audio-ak-spotify-com.akamaized.net'],
	youtube: ['youtube.com', 'youtu.be', 'googlevideo.com', 'ytimg.com', 'yt3.ggpht.com'],
	twitch: ['twitch.tv', 'jtvnw.net', 'ttvnw.net', 'twitchcdn.net'],
}

export class RoutesGenerator {
	private routesPath: string

	constructor() {
		this.routesPath = app.isPackaged
			? join(process.resourcesPath, 'binaries', 'aether', 'routes.conf')
			: join(__dirname, '..', '..', '..', '..', '..', 'binaries', 'aether', 'routes.conf')
	}

	generateForProfiles(
		games: GameProfile[],
		apps: AppProfile[]
	): string {
		const blockEntries: string[] = []
		const directEntries: string[] = []

		directEntries.push('private')
		directEntries.push('')

		for (const game of games) {
			const domains = GAME_DOMAINS[game.id] || []
			for (const domain of domains) {
				directEntries.push(domain)
			}
		}

		for (const app of apps) {
			if (app.type === 'voice') {
				const domains = VOICE_DOMAINS[app.id as keyof typeof VOICE_DOMAINS] || app.domains
				for (const domain of domains) {
					directEntries.push(domain)
				}
			} else if (app.type === 'media') {
				const domains = MEDIA_DOMAINS[app.id as keyof typeof MEDIA_DOMAINS] || app.domains
				for (const domain of domains) {
					directEntries.push(domain)
				}
			} else if (app.type === 'game') {
				for (const domain of app.domains) {
					directEntries.push(domain)
				}
			}
		}

		blockEntries.push('ads.example.com')
		blockEntries.push('keyword:doubleclick')
		blockEntries.push('keyword:adservice')
		blockEntries.push('keyword:analytics')
		blockEntries.push('port:25')
		blockEntries.push('port:587')

		return this.buildConfFile(blockEntries, directEntries)
	}

	generateFromExtractedDomains(domainsFilePath: string): string {
		const blockEntries: string[] = []
		const directEntries: string[] = []

		directEntries.push('private')
		directEntries.push('')

		if (existsSync(domainsFilePath)) {
			const content = readFileSync(domainsFilePath, 'utf-8')
			const lines = content.split('\n')

			for (const line of lines) {
				const trimmed = line.trim()
				if (!trimmed || trimmed.startsWith('#')) continue

				if (this.isGameDomain(trimmed)) {
					directEntries.push(trimmed)
				} else if (this.isMediaDomain(trimmed)) {
					directEntries.push(trimmed)
				} else if (this.isVoiceDomain(trimmed)) {
					directEntries.push(trimmed)
				} else if (this.isTrackerDomain(trimmed)) {
					blockEntries.push(trimmed)
				}
			}
		}

		blockEntries.push('')
		blockEntries.push('keyword:doubleclick')
		blockEntries.push('keyword:adservice')
		blockEntries.push('keyword:analytics')
		blockEntries.push('keyword:tracker')
		blockEntries.push('port:25')
		blockEntries.push('port:587')

		return this.buildConfFile(blockEntries, directEntries)
	}

	private buildConfFile(blockEntries: string[], directEntries: string[]): string {
		const sections: string[] = []

		sections.push('# MNX DNS - Aether Routing Rules')
		sections.push('# Generated by RoutesGenerator')
		sections.push('#')
		sections.push('# [block] = Traffic blocked/dropped')
		sections.push('# [direct] = Traffic routed directly (no tunnel)')
		sections.push('# Everything else goes through the Aether tunnel')
		sections.push('')

		sections.push('[block]')
		for (const entry of blockEntries) {
			sections.push(entry)
		}

		sections.push('')
		sections.push('[direct]')
		for (const entry of directEntries) {
			sections.push(entry)
		}

		return sections.join('\n')
	}

	private isGameDomain(domain: string): boolean {
		const gameKeywords = [
			'steam', 'valve', 'riotgames', 'epicgames', 'ubisoft',
			'ea.com', 'origin.com', 'rockstargames', 'blizzard',
			'battle.net', 'mojang', 'facepunch', 'playrust',
		]
		return gameKeywords.some((kw) => domain.includes(kw))
	}

	private isMediaDomain(domain: string): boolean {
		const mediaKeywords = [
			'spotify', 'youtube', 'youtu.be', 'googlevideo',
			'twitch', 'jtvnw', 'ttvnw', 'soundcloud',
		]
		return mediaKeywords.some((kw) => domain.includes(kw))
	}

	private isVoiceDomain(domain: string): boolean {
		const voiceKeywords = ['discord', 'teamspeak', 'mumble']
		return voiceKeywords.some((kw) => domain.includes(kw))
	}

	private isTrackerDomain(domain: string): boolean {
		const trackerKeywords = [
			'adservice', 'doubleclick', 'analytics', 'tracker',
			'adsense', 'adwords',
		]
		return trackerKeywords.some((kw) => domain.includes(kw))
	}

	saveRoutes(content: string): void {
		const dir = join(this.routesPath, '..')
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true })
		}
		writeFileSync(this.routesPath, content, 'utf-8')
		userLogger.info(`Routes saved to: ${this.routesPath}`)
	}

	getRoutesPath(): string {
		return this.routesPath
	}
}
